### ISSUE TITLE
assert failure

### ISSUE THREAD

**Issue by c-cube** [Gbury/mSAT#4]
`Fatal error: exception File "src/core/internal.ml", line 676, characters  16-22: Assertion failed`

- msat at 66707b58,
- smbc at 001b56ebb46. 
                            
run `./smbc.native --debug 1 examples/long_rev_sum5.lisp --max-depth 1010`
(around 6s environ)

**Comment by Gbury** [comment]
I think it is due to the analyze function expecting literals in decreasing order of decision level. I'll think about how to adapt the code.

**Comment by Gbury** [comment]
So, after a bit of investigating, this particular error appears to be because of a hidden precondition of the analyze function, which is that the conflict clause given should have at least one literal at the current level of decision (meaning that conflicts should be reported the earliest possible). This will be fixed soon.

**Comment by Gbury** [comment]
Closed by 7d57b3f1b5b4b5b659def9fef4e559e1fda4f7ec
